---

- name: "add postgresql repo key"
  apt_key:
    url: "{{ postgresql_gpg_key }}"
    state: present

- name: "add postgresql ce repo"
  apt_repository:
    filename: pgdg
    repo: "{{ postgresql_repo_deb }}"
    state: present

- name: install postgreSQL
  apt:
    name: "{{ postgreSQL_pkgs }}"
    update_cache: yes
    cache_valid_time: 3600
    state: present
  when: ansible_os_family == 'Debian'

- name: deploy postgres config file
  template:
    src: postgresql.conf.j2
    dest: /etc/postgresql/12/main/postgresql.conf
    owner: postgres
    group: postgres
    mode: 0644
  notify: restart postgres

- name: set postgreSQL admin user password
  become: yes
  become_user: postgres
  postgresql_user:
    name: "{{ postgreSQL_admin | default('postgres') }}"
    password: "{{ postgreSQL_admin_passwd }}"
  when: postgreSQL_admin_passwd is defined and postgreSQL_admin_passwd|length>0

- name: switch to postgre user
  block:
    - name: create postgresql databases
      import_tasks: "postgresql_db.yml"

    - name: create postgresql user
      import_tasks: "postgresql_user.yml"
  become: yes
  become_user: postgres
