---

- name: "add repo key"
  apt_key:
    url: "https://packages.cisofy.com/keys/cisofy-software-public.key"
    state: present

- name: "add cisofy-lynis repo"
  apt_repository:
    filename: cisofy-lynis
    repo: "deb https://packages.cisofy.com/community/lynis/deb/ stable main"
    update_cache: yes
    state: present

- name: "install lynis"
  apt:
    name: apt-transport-https,lynis
    state: latest
    update_cache: yes
    cache_valid_time: 3600
