---

- name: install redis server
  apt:
    name: redis-server
    state: latest
    update_cache: yes
    cache_valid_time: 3600

- name: deploy config
  template:
    src: redis_conf.j2
    dest: /etc/redis/redis.conf
    mode: 0640
    owner: redis
    group: redis
  notify:
    - restart redis

- name: enable redis-server
  systemd:
    name: redis-server
    enabled: yes