---
pdns_pkgs:
  - pdns-server
  - pdns-backend-mysql

pdns_schema:
  - "schema.mysql.sql"

pdns_backend: mariadb

pdns_db_connection_config:
  launch: gmysql
  gmysql-host: 127.0.0.1
  gmysql-port: 3306
  gmysql-dbname: pdns
  gmysql-user: pdnsadmin
  gmysql-password: password
  gmysql-dnssec: yes

pdns_database: pdns

pdns_conf:
  api: "yes"
  api-key: "yoursecretekey" # should be 64 char long random string  `pwgen -cns 64 1`
