---

- name: install CalmAV on Ubuntu/Debian
  apt:
    name: rkhunter
    state: latest
    update_cache: yes
    cache_valid_time: 3600

- name: update rkhunter database
  shell: rkhunter --propupd
