---

netbox_dependencies:
  - python3
  - python3-pip
  - python3-venv
  - python3-dev
  - build-essential
  - libxml2-dev
  - libxslt1-dev
  - libffi-dev
  - libpq-dev
  - libssl-dev
  - zlib1g-dev

netbox_repo: "https://github.com/netbox-community/netbox.git"

netbox_admin_user: admin 
netbox_admin_passwd: admin
netbox_admin_email: admin@exmaple.com