---

- name: "add repo key"
  apt_key:
    url: http://www.webmin.com/jcameron-key.asc
    state: present
  when: ansible_os_family == 'Debian'

- name: "add webadmin repo"
  apt_repository:
    filename: webadmin
    repo: deb http://download.webmin.com/download/repository sarge contrib
    update_cache: yes
    state: present
  when: ansible_os_family == 'Debian'

- name: install pkgs
  apt:
    name: "{{ pkgs_deb }}"
  when: ansible_os_family == 'Debian'

- name: Import Webadmin RedHat/Centos Repo key
  rpm_key:
    state: present
    key: http://www.webmin.com/jcameron-key.asc
  when: ansible_os_family == 'RedHat'

- name: add webadmin RedHat/Centos repo
  yum_repository:
    name: Webmin Distribution Neutral
    description: webadmin repo
    file: webadmin
    mirrorlist: https://download.webmin.com/download/yum/mirrorlist
    enabled: yes
  when: ansible_os_family == 'RedHat'

- name: install webadmin on RedHat/Centos
  yum:
    name:  "{{ pkgs_rpm }}"
    state: present
  when: ansible_os_family == 'RedHat'

- name: install virtualmin
  block:

    - name: download virutalmin install sh
      get_url:
        url: http://software.virtualmin.com/gpl/scripts/install.sh
        dest: /var/tmp/virtualmin_install.sh"
    
    - name: install virutalmin
      shell: |
        set timeout 300
        spawn bash -c {/var/tmp/virtualmin_install.sh}

        expect "Continue? (y/n)"
        send "y\r"
      when: ansible_memtotal_mb >= 1572
    
    - name: install virutalmin
      shell: |
        set timeout 300
        spawn bash -c {/var/tmp/virtualmin_install.sh}

        expect "Continue? (y/n)"
        send "y\r"

        expect "Would you like to continue? If you continue, you will be given(.*)"
        send "y\r"

        expect -re "Would you like for me to try to create a swap file?(.*)"
        send "y\r"
      when: ansible_memtotal_mb <= 1572
  when: install_virtualmin