# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'
require 'rbconfig'

vagrant_hosts = ENV['VAGRANT_HOSTS'] ? ENV['VAGRANT_HOSTS'] : 'vagrant-hosts.yaml'
servers = YAML.load_file(File.join(__dir__, vagrant_hosts))
DEFAULT_BOX = "ubuntu/bionic64"

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # |
  # | :::::: Vagrant Plugins
  # |
  config.vagrant.plugins = [{"vagrant-vbguest" => {"version" => "0.28.0"}}, {"landrush" => {"version" => "1.3.2"}}]

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = servers["vagrant-vbguest"]||= true
  end

  if Vagrant.has_plugin?("landrush")
    config.landrush.enabled = servers["landrush"]["enabled"]
    config.landrush.guest_redirect_dns = servers["landrush"]["guest_redirect_dns"]
    config.landrush.tld = servers["landrush"]["tld"]
  end

  servers["hosts"].each do |server|
    config.vm.define server["name"] do |srv|
      srv.vm.box = server["box"] ||= DEFAULT_BOX

      # |
      # | :::::: Box
      # |

      if server["box_version"]
        srv.vm.box_version = server["box_version"]
      end

      if server["box_check_update"]
        srv.vm.box_check_update = server["box_check_update"]
      end

      # | ············································································
      # | :::::: VM Setup
      # | ············································································

      srv.vm.provider "virtualbox" do |vb|
        vb.name = server["name"]

        if server["gui"]
          vb.gui      = server["gui"]
        end

        vb.customize ["modifyvm", :id, "--usb", "off"]
        vb.customize ["modifyvm", :id, "--usbehci", "off"]

        vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
        vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
        vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        #vb.customize ["modifyvm", :id, "--natdnshostresolver2", "on"]

        if server["gui"]
          vb.gui = server["gui"]
        end
        if defined? server["ram"]
          if server["ram"] == "auto"
            host = RbConfig::CONFIG['host_os']
            if host =~ /darwin/
              mem = `sysctl -n hw.memsize`.to_i / 1024 / 1024 / 4
            elsif host =~ /linux/
              mem = `grep 'MemTotal' /proc/meminfo | sed -e 's/MemTotal://' -e 's/ kB//'`.to_i / 1024 / 4
            else
              mem = 1024
            end
            vb.memory = mem
          else
            vb.memory = server["ram"]
          end
        else
          vb.memory = 512
        end
        if defined? server["cpus"]
          if server["cpus"] == "auto"
              host = RbConfig::CONFIG['host_os']
              if host =~ /darwin/
                  cpus = `sysctl -n hw.ncpu`.to_i
              elsif host =~ /linux/
                  cpus = `nproc`.to_i
              else
                  cpus = 2
              end
              vb.cpus   = cpus
          else
              vb.cpus   = server["cpus"]
          end
        else
          vb.cpus = 1
        end
      end
# Check if a specific hostname is set else set the name of the vm
      if server["hostname"]
        srv.vm.hostname = server["hostname"]
      else
        srv.vm.hostname = server["name"]
      end

      # |
      # | :::::: Network
      # |
      if server["private_network"]
        server['private_network'].each do |private_network|
          if private_network["ip_private"] && private_network["auto_config"]
            srv.vm.network "private_network",
                ip:  private_network["ip_private"],
                auto_config: private_network["auto_config"]
          elsif private_network["ip_private"]
            srv.vm.network "private_network",
                ip: private_network["ip_private"]
          else private_network["type"]
            srv.vm.network "private_network",
                type: private_network["type"]
          end
        end
      end

      if defined? server["public_network"]["ip_public"]
        if server["public_network"]["ip_public"] == "auto"
            srv.vm.network "public_network"
        elsif server["public_network"]["ip_public"] == "true"
            srv.vm.network "public_network",
                use_dhcp_assigned_default_route: true
        elsif server["public_network"]["ip_public"] && server["public_network"]["bridge"]
            srv.vm.network "public_network",
                ip:     server["public_network"]["ip_public"],
                bridge: server["public_network"]["bridge"]
        else
            srv.vm.network "public_network",
                ip: server["public_network"]["ip_public"]
        end
      end

      # |
      # | :::::: Ports forwarded
      # |

      if server["ports"]
        server["ports"].each do |ports|
            srv.vm.network "forwarded_port",
            guest: ports["guest"],
            host: ports["host"],
            auto_correct: true
        end
      end
      # |
      # | :::::: Folder Sync
      # |
      if server["syncDir"]
        server['syncDir'].each do |syncDir|
          if syncDir["owner"] && syncDir["group"]
              srv.vm.synced_folder syncDir["host"],
              syncDir["guest"],
              owner: "#{syncDir["owner"]}",
              group: "#{syncDir["group"]}",
              mount_options:["dmode=#{syncDir["dmode"]}",
              "fmode=#{syncDir["fmode"]}"],
              create: true
          else
              srv.vm.synced_folder syncDir['host'],
              syncDir['guest'],
              create: true
          end
        end
      end

      # |
      # | :::::: Folder Sync
      # |
      if server["disks"]
        server['disks'].each do |disks|
          srv.vm.disk :disk, 
          name: disks['name'], 
          size: disks['size']
        end
      end

# | ············································································
# | : Provisioning
# | ············································································
      # |
      # | :::::: Provisions - Bash
      # |
      if server["bash"]
        srv.vm.provision :shell, :path => server["bash"]
      end

      # |
      # | :::::: Provisions - files
      # |
      if server["files"]
        server["files"].each do |files|
          srv.vm.provision "file", source: files["source"], destination: files["destination"]
          srv.vm.boot_timeout = 240
        end
      end
      # |
      # | :::::: Provisions - Puppet
      # |
      if server["puppet"]
        srv.vm.provision :puppet do |puppet|
          if server["puppet"]["modules"]
            puppet.module_path = server["puppet"]["modules"]
          end
          if server["puppet"]["manifests_path"]
            puppet.manifests_path = server["puppet"]["manifests_path"]
          end
          if server["puppet"]["manifests_file"]
            puppet.manifest_file = server["puppet"]["manifests_file"]
          end
        end
      end
      # |
      # | :::::: Provisions - Asible
      # |
      if server["ansible"]
        srv.vm.provision :ansible do |ansible|
          if server["ansible"]["verbose"]
            ansible.verbose = server["ansible"]["verbose"]
          end
          if server["ansible"]["playbook"]
            ansible.playbook = server["ansible"]["playbook"]
          end
          if server["ansible"]["inventory_path"]
            ansible.inventory_path = server["ansible"]["inventory_path"]
          end
          if server["ansible"]["host_key_checking"]
            ansible.host_key_checking = server["ansible"]["host_key_checking"]
          end
          if server["ansible"]["limit"]
            ansible.limit = server["ansible"]["limit"]
          end
        end
      end
      # |
      # | :::::: Provisions - Salt
      # |
      if server["salt"]
        srv.vm.provision :salt do |salt|
          if server["salt"]["install_master"]
            salt.install_master = server["salt"]["install_master"]
          end
          if server["salt"]["install_type"]
            salt.install_type = server["salt"]["install_type"]
          else
            salt.install_type = "stable"
          end
          if server["salt"]["no_minion"]
            salt.no_minion = ["salt"]["no_minion"]
          end
          if server["salt"]["install_syncdir"]
            salt.install_syncdir = ["salt"]["install_syncdir"]
          end
          if server["salt"]["install_type"] == "git" and ["salt"]["install_args"] != "develop"
            salt.install_args = ["salt"]["install_args"]
          end
          if server["salt"]["always_install"]
            salt.always_install  = ["salt"]["always_install"]
          end
          if server["salt"]["bootstrap_script"]
            salt.bootstrap_script = ["salt"]["bootstrap_script"]
          end
          if server["salt"]["bootstrap_script"] and server["salt"]["bootstrap_options"]
            salt.bootstrap_script = ["salt"]["bootstrap_options"]
          end
          if server["salt"]["version"]
            salt.version = server["salt"]["version"]
          end
          if server["salt"]["python_version"]
            salt.python_version = server["salt"]["python_version"]
          end
          if server["salt"]["run_highstate"]
            salt.run_highstate = server["salt"]["run_highstate"]
          end
          if server["salt"]["colorize"]
            salt.colorize = server["salt"]["colorize"]
          end
          if server["salt"]["log_level"]
            salt.log_level = server["salt"]["log_level"]
          end
          if server["salt"]["verbose"]
            salt.verbose = server["salt"]["verbose"]
          end
        end
        salt_master = server["salt"]["salt_master"]
        srv.trigger.after [:up, :provision, :reload] do |tu|
          tu.name = "accept all keys"
          tu.info = "accept minion key on master"
          tu.run = {inline: "vagrant ssh #{salt_master} -- sudo /usr/bin/salt-key -y -A"}
        end
        server_name = server["name"]
        if server["name"] != server["salt"]["salt_master"]
          srv.trigger.after :destroy do |td|
            td.name = "remove keys"
            td.info = "remove minion key on master after destroy"
            td.run = {inline: "vagrant ssh #{salt_master} -- sudo /usr/bin/salt-key -y -d #{server_name}"}
          end
        end
      end
    end
  end
end
