---

- name: Get cksum of /var/lib/rabbitmq/.erlang.cookie.old
  stat:
    path : "/var/lib/rabbitmq/.erlang.cookie"
  register: myfirstfile

- name: Get cksum of /var/lib/rabbitmq/.erlang.cookie.old
  stat:
    path : "/var/lib/rabbitmq/.erlang.cookie.old"
  register: mysecondfile

- name: Current SHA1
  set_fact:
    mf1sha1: "{{ myfirstfile.stat.checksum }}"

- name: Current SHA1
  set_fact:
    mf2sha1: "{{ mysecondfile.stat.checksum }}"

- name: configure rabbitmq cluster
  block:
    - name: restart rabbitmq server
      service:
        name: rabbitmq-server
        state: restarted

    - name: stop rabbitmq app
      shell: rabbitmqctl stop_app

    - name: reset rabbitmq app
      shell: rabbitmqctl reset

    - name: add this node to cluster
      shell: rabbitmqctl join_cluster rabbit@{{ rabbitmq_cluster_master }}
      register: join_cluster_output
      ignore_errors: True

    - name: skip fail if the node is already a member of the cluster
      fail: 
        msg: "join_cluster failed but node is not already a member"
      when: ("'already_member' not in join_cluster_output.stderr") and
            (join_cluster_output.rc != 0)

    - name: start rabbitmq app
      shell: rabbitmqctl start_app
  when: mf1sha1 != mf2sha1