---

- include: repo.yml
  tags: repository

- include: packages.yml
  tags: packages

- include: config-cluster.yml
  when: rabbitmq_create_cluster

- include: config.yml

- include: service.yml

- include: cluster.yml
  when: (rabbitmq_create_cluster == true) and ( ansible_fqdn != rabbitmq_cluster_master_fqdn )

- include: rabbitmq.yml
  when: 'not rabbitmq_create_cluster or (ansible_fqdn == rabbitmq_cluster_master_fqdn)'

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers
