---

- name: "add docker repo key"
  apt_key:
    url: "{{ docker_gpg_key }}"
    id: "{{ docker_repo_key_id }}"
    state: present

- name: "add docker ce repo"
  apt_repository:
    filename: docker_stable
    repo: "{{ docker_repo_deb }}"
    state: present

- name: "install docker-ce"
  apt:
    name: "{{ docker_packages }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  notify:
    - start docker