---
- name: "Manage Databases"
  mysql_db:
    login_host: "{{ item.login_host | default(omit) }}"
    login_port: "{{ item.login_port | default(omit) }}"
    login_user: "{{ item.login_user | default(omit) }}"
    login_password: "{{ item.login_password | default(mariadb_root_password|default(omit)) }}"
    login_unix_socket: "{{ item.login_socket | default('/var/run/mysqld/mysqld.sock') }}"
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ mariadb_databases | flatten(levels=1) }}"
  when: mariadb_databases is defined and mariadb_databases|length>0
