---
- import_tasks: "install.yml"
  tags: install
- import_tasks: "secure_install.yml"
  when: secure_install
  tags: install
- import_tasks: "configure.yml"
  tags: config
- import_tasks: "databases.yml"
  tags: createdb
- import_tasks: "users.yml"
  tags: dbuser
