---

- name: install netplan
  apt:
    name: "{{ netplan_pkgs }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == 'Debian' 
  register: np
  until: np is successful

- name: remove all not defined netplan configs
  block:
    - find: 
        paths: "/etc/netplan/"
        recurse: yes
      register: find

    - file:
        path: "{{ item.path }}"
        state: absent
      when: not item.path | basename| splitext | first  in netplan_config
      loop: "{{ find.files }}"
  when: remove_old_configs is defined and remove_old_configs

- name: deploy netplan interface config
  template:
    src: interface.j2
    dest: "/etc/netplan/{{ item.key }}.yaml"
    mode: 0644
    owner: root
    group: root
  loop: "{{ netplan_config | dict2items }}"
  when: netplan_config != []
  notify: netplan generate config
