---

- name: "add repo key"
  apt_key:
    url: "https://packages.wazuh.com/key/GPG-KEY-WAZUH"
    state: present

- name: "add hashicorp repo"
  apt_repository:
    filename: wazuh
    repo: "deb https://packages.wazuh.com/3.x/apt/ stable main"
    update_cache: yes
    state: present

- name: "install wazuh-manger"
  apt:
    name: "{{ wazuh_pkgs }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600

- name: "install wazuh-api"
  apt:
    name: "{{ wazuh-api_pkgs }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  when: wazuh_api_install

- name: check if filebeat is installed
  stat:
    path: /usr/bin/filebeat
  register: filebeat

- name: deploy wazuh filebeat config
  copy:
    src: filebeat.yaml
    dest: /etc/filebeat/filebeat.yml
    mode: 0600
    owner: root
    group: root
  when: filebeat.stat.exists

- name: secure wazuh
  shell:
    cmd: "node htpasswd -c {{ wazuh_api_password }} {{ wazuh_api_user }}"
    chdir: /var/ossec/api/configuration/auth
  when: wazuh_api_password is defined and wazuh_api_password|length>0 and wazuh_api_user is defined
  notify:
    - restart wazuh-api
    - restart wazuh-manager