---

default_ufw:
  IPV6: "yes"
  DEFAULT_INPUT_POLICY: "DROP"
  DEFAULT_OUTPUT_POLICY: "ACCEPT"
  DEFAULT_FORWARD_POLICY: "DROP"
  DEFAULT_APPLICATION_POLICY: "SKIP"
  MANAGE_BUILTINS: "no"
  IPT_SYSCTL: "/etc/ufw/sysctl.conf"
  IPT_MODULES: "nf_conntrack_ftp
    nf_nat_ftp
    nf_conntrack_netbios_ns"

ufw_rules:
  - state: enabled
    policy: deny
    direction: incoming
  - policy: allow
    direction: outgoing
  - rule: allow
    from_ip: any
    to_port: '80'
    proto: tcp
  - rule: allow
    name: OpenSSH
