---

go_path: "/usr/local/go/bin"
dest_download: "/var/tmp/"
url: "https://golang.org/dl/go1.15.6.linux-amd64.tar.gz"
checksum: "sha256:3918e6cc85e7eaaa6f859f1bdbaac772e7a825b0eb423c63d3ae68b21f84b844"
