---
- name: install fail2ban
  apt:
    name: fail2ban
    state: latest
    update_cache: yes
    cache_valid_time: 86400
  when: ansible_facts['os_family'] == "Debian"
  notify:
    - start fail2ban

- name: install fail2ban RedHat
  yum:
    name: fail2ban
    state: latest
  when: ansible_facts['os_family'] == "RedHat"
  notify:
    - start fail2ban

- name: deploy configuration for fail2ban
  template:
    dest: "/etc/fail2ban/{{ item.key }}"
    src: config.j2
  loop: "{{ fail2ban_config | dict2items }}"
  when: fail2ban_config is defined and fail2ban_config|length>0
  notify:
    - restart fail2ban
