---

- name: create step log directory
  file:
    path: /var/log/step-ca
    state: directory
    owner: step
    group: step

- name: deploy step-ca.service file
  template:
    src: step-ca.service.j2
    dest: /etc/systemd/system/step-ca.service 
    owner: root
    group: root
    mode: 0644
  register: service

- name: reload systemd daemon
  systemd:
    daemon_reload: yes
  when: service is changed