---

awx_dependencies_pkgs:
  - nodejs
  - npm
  - git
  - pwgen
  - vim

python_version: 3

awx_install_dir: /opt/awx

awx_config:
  inventory:
    dockerhub_base: ansible
    awx_task_hostname: awx
    awx_web_hostname: awxweb
    postgres_data_dir: "~/.awx/pgdocker"
    host_port: 80
    host_port_ssl: 443
    docker_compose_dir: "~/.awx/awxcompose"
    pg_username: awx
    pg_password: awxpass
    pg_database: awx
    pg_port: 5432
    admin_user: admin
    admin_password: password
    create_preload_data: True
    secret_key: t7Ny0e8ESBbfXxoEsow683zsVjhklG
