---

- name: install memcached
  apt:
    name: "{{ memcached_pkgs }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600

- name: deploy memcached config
  template:
    src: memcached.conf.j2
    dest: /etc/memcached.conf
    mode: 0644
    owner: root
    group: root
  notify: restart memcached