---

configure_openldap: true


slapd_debconf:
  - question: slapd/no_configuration
    value: false
    vtype: boolean
  - question: slapd/domain
    value: vagrant.test
    vtype: text
  - question: shared/organization
    value: vagrant.test
    vtype: text
  - question: slapd/password1
    value: admin1234
    vtype: password
  - question: slapd/password2
    value: admin1234
    vtype: password
  - question: slapd/purge_database
    value: true
    vtype: boolean
  - question: slapd/move_old_database
    value: true
    vtype: boolean
